[project]
name = "nonebot_plugin_nya_cook_menu"
version = "0.1.8"
description = "Nonebot2 喵喵自记菜谱，记录生活中的小菜谱"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "nonebot-adapter-onebot>=2.0.0",
    "nonebot2>=2.0.0rc1",
    "Pillow>=9.0.0",
]
authors = [
    {name = "nikissXI", email = "1299577815@qq.com"},
]
license = {text = "MIT"}

[project.urls]
Homepage = "https://github.com/nikissXI/nonebot_plugins/tree/main/nonebot_plugin_nya_cook_menu"
Repository = "https://github.com/nikissXI/nonebot_plugins/tree/main/nonebot_plugin_nya_cook_menu"
Documentation = "https://github.com/nikissXI/nonebot_plugins/tree/main/nonebot_plugin_nya_cook_menu#README.md"

[[tool.uv.index]]
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"
default = true

[tool.setuptools.packages.find]
include = ["nonebot_plugin_nya_cook_menu"]

[build-system]
requires = ["setuptools>=65.5", "wheel"]
build-backend = "setuptools.build_meta"
